name: Container release
on:
  push:
    tags: '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [debian, alpine]
    steps:
      - name: Set hedgedoc version from tag name
        run: echo "$GITHUB_REF" | sed -e 's~refs/tags/\(.*\)~HEDGEDOC_VERSION=\1~' >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v2

      - uses:  hugopeixoto/ghaction-docker-meta@v2
        name: Docker meta
        id: docker_meta
        with:
          images: quay.io/hugopeixoto/hedgedoc
          flavor: ${{ matrix.base }}
          main-flavor: ${{ matrix.base == 'debian' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ matrix.base }}/Dockerfile
          build-args: |
            VERSION=${{ env.HEDGEDOC_VERSION }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
