name: Container release
on:
  push:
    branches: '**'

jobs:
  multi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [debian, alpine]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ matrix.base }}/Dockerfile
          build-args: |
            VERSION=1.6.0
          platforms: linux/amd64
          push: true
          tags: |
            quay.io/hugopeixoto/hedgedoc:${{ matrix.base }}
            quay.io/hugopeixoto/hedgedoc:1.6.0-${{ matrix.base }}
